### ISSUE TITLE
Broken type hint

### ISSUE THREAD

**Issue by michalk8** [scverse/squidpy#553]
## Description

Can't import squidpy on 3.8, introduced by #551 , problem is `type[...]` instead of `Type[...]`.

## Minimal reproducible example

```python
import squidpy  # on Python3.8
```

## Traceback

<details>

```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/projects/helmholtz/squidpy/squidpy/__init__.py", line 1, in <module>
    from squidpy import gr, im, pl, read, datasets
  File "/opt/projects/helmholtz/squidpy/squidpy/gr/__init__.py", line 2, in <module>
    from squidpy.gr._build import spatial_neighbors
  File "/opt/projects/helmholtz/squidpy/squidpy/gr/_build.py", line 26, in <module>
    from squidpy._docs import d, inject_docs
  File "/opt/projects/helmholtz/squidpy/squidpy/_docs.py", line 7, in <module>
    from squidpy._constants._pkg_constants import Key
  File "/opt/projects/helmholtz/squidpy/squidpy/_constants/_pkg_constants.py", line 8, in <module>
    from squidpy._constants._constants import Processing, SegmentationBackend
  File "/opt/projects/helmholtz/squidpy/squidpy/_constants/_constants.py", line 4, in <module>
    from squidpy._constants._utils import ModeEnum
  File "/opt/projects/helmholtz/squidpy/squidpy/_constants/_utils.py", line 7, in <module>
    def _pretty_raise_enum(cls: type["ModeEnum"], fun: Callable[..., Any]) -> Callable[..., Any]:
TypeError: 'type' object is not subscriptable
```

</details>

## Version

https://github.com/scverse/squidpy/commit/9dd5f16e306136cd274e11f4def3a995486aa00d

**Comment by giovp** [comment]
my bad, updated pyupgrade to 3.9 instead of keeping 3.8
