### ISSUE TITLE
Can we change where omnipath database will be written to?

### ISSUE THREAD

**Issue by frankligy** [scverse/squidpy#556]
When I was running `sq.gr.ligrec` function, It seems that omnipath ini file had to be written in my /Users/xxxx/.config folder. But since I don't have permission to write file in this folder, neither can I modify the permission using `chmod`, I am not able to get this function running.

```
sq.gr.ligrec(adata_tmp,n_perms=100,cluster_key="dominant",use_raw=False)
Traceback (most recent call last):
  File "/opt/anaconda3/envs/sc_env/lib/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/opt/anaconda3/envs/sc_env/lib/python3.7/site-packages/squidpy/gr/_ligrec.py", line 655, in ligrec
    .prepare(interactions, complex_policy=complex_policy, **kwargs)
  File "/opt/anaconda3/envs/sc_env/lib/python3.7/site-packages/squidpy/gr/_ligrec.py", line 593, in prepare
    from omnipath.interactions import import_intercell_network
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/opt/anaconda3/envs/sc_env/lib/python3.7/site-packages/omnipath/__init__.py", line 2, in <module>
    from omnipath._core.utils import options  # from_first in isort is important here
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/opt/anaconda3/envs/sc_env/lib/python3.7/site-packages/omnipath/_core/utils/__init__.py", line 1, in <module>
    from omnipath._core.utils._options import options
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/opt/anaconda3/envs/sc_env/lib/python3.7/site-packages/omnipath/_core/utils/_options.py", line 259, in <module>
    options = Options.from_config()
  File "/opt/anaconda3/envs/sc_env/lib/python3.7/site-packages/omnipath/_core/utils/_options.py", line 180, in from_config
    return cls().write()
  File "/opt/anaconda3/envs/sc_env/lib/python3.7/site-packages/omnipath/_core/utils/_options.py", line 247, in write
    with open(self.config_path, "w") as fout:
PermissionError: [Errno 13] Permission denied: '/Users/E0532183/.config/omnipathdb.ini'
```
I tried to check how to change this behavior using the additional arguments and also looked at the omnipath doc, but I didn't find a satisfied way to do so. Would you mind providing any hint here?

Thank you,
Frank

**Comment by michalk8** [comment]
Hi @frankligy , could you please open this issue in https://github.com/saezlab/omnipath/issues?

**Comment by frankligy** [comment]
Thank you, I will do!
