### ISSUE TITLE
example data in figshare 403: Forbidden

### ISSUE THREAD

**Issue by biobai** [scverse/squidpy#764]
## Example data in figshare could not be downloaded

```python
>>> import squidpy as sq
>>> adata = sq.datasets.slideseqv2()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 17, in slideseqv2
  File "/PUBLIC/gomics/baiyouhuang/miniconda3/envs/nest/lib/python3.10/site-packages/squidpy/datasets/_utils.py", line 87, in downl
oad
    data = self._download(fpath=fpath, backup_url=self.url, **kwargs)
  File "/PUBLIC/gomics/baiyouhuang/miniconda3/envs/nest/lib/python3.10/site-packages/squidpy/datasets/_utils.py", line 127, in _dow
nload
    return read(filename=fpath, backup_url=backup_url, **kwargs)
  File "/PUBLIC/gomics/baiyouhuang/miniconda3/envs/nest/lib/python3.10/site-packages/scanpy/readwrite.py", line 112, in read
    return _read(
  File "/PUBLIC/gomics/baiyouhuang/miniconda3/envs/nest/lib/python3.10/site-packages/scanpy/readwrite.py", line 707, in _read
    is_present = _check_datafile_present_and_download(filename, backup_url=backup_url)
  File "/PUBLIC/gomics/baiyouhuang/miniconda3/envs/nest/lib/python3.10/site-packages/scanpy/readwrite.py", line 978, in _check_data
file_present_and_download
    _download(backup_url, path)
  File "/PUBLIC/gomics/baiyouhuang/miniconda3/envs/nest/lib/python3.10/site-packages/scanpy/readwrite.py", line 940, in _download
    with urlopen(Request(url, headers={"User-agent": "scanpy-user"})) as resp:
  File "/PUBLIC/gomics/baiyouhuang/miniconda3/envs/nest/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/PUBLIC/gomics/baiyouhuang/miniconda3/envs/nest/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/PUBLIC/gomics/baiyouhuang/miniconda3/envs/nest/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/PUBLIC/gomics/baiyouhuang/miniconda3/envs/nest/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/PUBLIC/gomics/baiyouhuang/miniconda3/envs/nest/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/PUBLIC/gomics/baiyouhuang/miniconda3/envs/nest/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

How to obtain the example data now?

**Comment by giovp** [comment]
hi @biobai  unfortunately I am not sure what is your issue. I will close this due to inactivity
