### ISSUE TITLE
matplotlib update leads to import error

### ISSUE THREAD

**Issue by LouisK92** [scverse/squidpy#827]
## Description

matplotlib release v3.9.0 introduces an import error for me when import squidpy.

Downgrading to v3.8.4 solves the issue. (`pip install matplotlib==3.8.4`)

## Minimal reproducible example

```python
import squidpy
```

## Traceback

```pytb
...
    import squidpy as sq
  File "/.../lib/python3.10/site-packages/squidpy/__init__.py", line 3, in <module>
    from squidpy import datasets, gr, im, pl, read, tl
  File "/.../lib/python3.10/site-packages/squidpy/pl/__init__.py", line 12, in <module>
    from squidpy.pl._spatial import spatial_scatter, spatial_segment
  File "/.../lib/python3.10/site-packages/squidpy/pl/_spatial.py", line 17, in <module>
    from squidpy.pl._spatial_utils import (
  File "/.../lib/python3.10/site-packages/squidpy/pl/_spatial_utils.py", line 29, in <module>
    from matplotlib.cm import get_cmap
ImportError: cannot import name 'get_cmap' from 'matplotlib.cm'
```

## Version

1.4.1

**Comment by earmingol** [comment]
Same error here, this make fail the CI of a tool I'm developing.

**Comment by andrew-weisman** [comment]
Same here, on Ubuntu 22.04.4 LTS, here is how I reproduce:

```bash
sudo apt-get update && sudo apt-get upgrade
conda update -n base -c conda-forge conda
conda create -n barebones python pip pygeos
conda activate barebones
pip install matplotlib squidpy
python
```

```python
import squidpy
```

```text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/XXXX/programs/miniconda3/envs/barebones/lib/python3.11/site-packages/squidpy/__init__.py", line 3, in <module>
    from squidpy import datasets, gr, im, pl, read, tl
  File "/home/XXXX/programs/miniconda3/envs/barebones/lib/python3.11/site-packages/squidpy/pl/__init__.py", line 12, in <module>
    from squidpy.pl._spatial import spatial_scatter, spatial_segment
  File "/home/XXXX/programs/miniconda3/envs/barebones/lib/python3.11/site-packages/squidpy/pl/_spatial.py", line 17, in <module>
    from squidpy.pl._spatial_utils import (
  File "/home/XXXX/programs/miniconda3/envs/barebones/lib/python3.11/site-packages/squidpy/pl/_spatial_utils.py", line 29, in <module>
    from matplotlib.cm import get_cmap
ImportError: cannot import name 'get_cmap' from 'matplotlib.cm' (/home/XXXX/programs/miniconda3/envs/barebones/lib/python3.11/site-packages/matplotlib/cm.py)
```

**Comment by michalk8** [comment]
Thanks for pointing this out, will fix over the weekend!

**Comment by giovp** [comment]
hi all, thank you for reporting, this has been fixed in the latest release on pypi

**Comment by earmingol** [comment]
It works for me too, now the CI iof my tool s passing the tests
