### ISSUE TITLE
No matching definition for argument type

### ISSUE THREAD

**Issue by wangjiawen2013** [scverse/squidpy#867]
Hi,
When I run `sq.gr.nhood_enrichment(sdata["table"], n_jobs=10, cluster_key='id')`, the following error occurred:
```
No matching definition for argument type(s) readonly array(uint32, 1d, C), array(uint32, 1d, C), array(uint32, 1d, C)
  File "/home/wangjw/data/work/spatial/pipeline.smk", line 317, in __rule_spatial_graph
  File "/home/wangjw/programs/miniconda3/envs/py311/lib/python3.11/site-packages/squidpy/gr/_nhood.py", line 186, in nhood_enrichment
  File "/home/wangjw/programs/miniconda3/envs/py311/lib/python3.11/site-packages/squidpy/_utils.py", line 171, in wrapper
  File "/home/wangjw/programs/miniconda3/envs/py311/lib/python3.11/site-packages/joblib/parallel.py", line 1952, in __call__
  File "/home/wangjw/programs/miniconda3/envs/py311/lib/python3.11/site-packages/joblib/parallel.py", line 1595, in _get_outputs
  File "/home/wangjw/programs/miniconda3/envs/py311/lib/python3.11/site-packages/joblib/parallel.py", line 1699, in _retrieve
  File "/home/wangjw/programs/miniconda3/envs/py311/lib/python3.11/site-packages/joblib/parallel.py", line 1734, in _raise_error_fast
  File "/home/wangjw/programs/miniconda3/envs/py311/lib/python3.11/site-packages/joblib/parallel.py", line 736, in get_result
  File "/home/wangjw/programs/miniconda3/envs/py311/lib/python3.11/site-packages/joblib/parallel.py", line 754, in _return_or_raise
  File "/home/wangjw/programs/miniconda3/envs/py311/lib/python3.11/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
^CException ignored in: <module 'threading' from '/home/wangjw/programs/miniconda3/envs/py311/lib/python3.11/threading.py'>
Traceback (most recent call last):
```
Is it relate to the parameters `numba_parallel` and `backend` ?

**Comment by p-lombard** [comment]
I'm experiencing the same issue!

**Comment by wangjiawen2013** [comment]
Setting `n_jobs=1` can avoid the bug.

**Comment by giovp** [comment]
can you post the whole traceback?

**Comment by wangjiawen2013** [comment]
I don't know, I am switching to AI and have not worked on bioinformatics for many months.
