### ISSUE TITLE
Error in import squidpy: cannot import name 'SparseCSCView' from 'anndata._core.views'

### ISSUE THREAD

**Issue by diego-iac** [scverse/squidpy#928]
## Description

Hi, I'm trying to use squidpy but when I try to import it returns an error. It seems to search for a function in anndata which I couldn't find. I might just have misunderstood the error, and if that's the case, I apologize. Could you please help me understand or resolve this issue?
Thanks in advance
...

## Minimal reproducible example

```python
#the package was downloaded from conda with other packages like sainsc. I'm running the code in this environment on Spyder 6. Anndata version=0.11.1
import squidpy as sq
...
```

## Traceback

<details>

```pytb
ImportError                               Traceback (most recent call last)
Cell In[18], line 1
----> 1 import squidpy as sq

File ~/anaconda3/envs/sainsc/lib/python3.12/site-packages/squidpy/__init__.py:5
      1 from __future__ import annotations
      3 from importlib import metadata
----> 5 from squidpy import datasets, gr, im, pl, read, tl
      7 try:
      8     md = metadata.metadata(__name__)

File ~/anaconda3/envs/sainsc/lib/python3.12/site-packages/squidpy/gr/__init__.py:5
      1 """The graph module."""
      3 from __future__ import annotations
----> 5 from squidpy.gr._build import spatial_neighbors
      6 from squidpy.gr._ligrec import ligrec
      7 from squidpy.gr._nhood import centrality_scores, interaction_matrix, nhood_enrichment

File ~/anaconda3/envs/sainsc/lib/python3.12/site-packages/squidpy/gr/_build.py:31
     29 from squidpy._docs import d, inject_docs
     30 from squidpy._utils import NDArrayA
---> 31 from squidpy.gr._utils import (
     32     _assert_categorical_obs,
     33     _assert_positive,
     34     _assert_spatial_basis,
     35     _save_data,
     36 )
     38 __all__ = ["spatial_neighbors"]
     41 @d.dedent
     42 @inject_docs(t=Transform, c=CoordType)
     43 def spatial_neighbors(
   (...)
     56     copy: bool = False,
     57 ) -> tuple[csr_matrix, csr_matrix] | None:

File ~/anaconda3/envs/sainsc/lib/python3.12/site-packages/squidpy/gr/_utils.py:12
     10 import pandas as pd
     11 from anndata import AnnData
---> 12 from anndata._core.views import ArrayView, SparseCSCView, SparseCSRView
     13 from anndata.utils import make_index_unique
     14 from pandas import CategoricalDtype

ImportError: cannot import name 'SparseCSCView' from 'anndata._core.views' (/home/onco-lab/anaconda3/envs/sainsc/lib/python3.12/site-packages/anndata/_core/views.py)
...
```

</details>

## Version

# Name                    Version                   Build  Channel
squidpy                   1.5.0              pyhd8ed1ab_0    conda-forge

Anndata version=0.11.1
...

**Comment by HeesooSong** [comment]
https://github.com/scverse/squidpy/issues/915

I also had the same issue and could fix it by installing version 1.6.2.

**Comment by LuisHeinzlmeier** [comment]
Seems like this error is back :)

Code
```
>>> mamba create -n test "python>=3.14" squidpy
>>> mamba activate test
>>> import squidpy as sq
```

Traceback
```
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import squidpy as sq
  File "/Users/luisheinzlmeier/miniforge3/envs/test/lib/python3.14/site-packages/squidpy/__init__.py", line 1, in <module>
    from squidpy import gr, im, pl, read, datasets
  File "/Users/luisheinzlmeier/miniforge3/envs/test/lib/python3.14/site-packages/squidpy/gr/__init__.py", line 2, in <module>
    from squidpy.gr._build import spatial_neighbors
  File "/Users/luisheinzlmeier/miniforge3/envs/test/lib/python3.14/site-packages/squidpy/gr/_build.py", line 28, in <module>
    from squidpy.gr._utils import (
    ...<4 lines>...
    )
  File "/Users/luisheinzlmeier/miniforge3/envs/test/lib/python3.14/site-packages/squidpy/gr/_utils.py", line 11, in <module>
    from anndata._core.views import ArrayView, SparseCSCView, SparseCSRView
ImportError: cannot import name 'SparseCSCView' from 'anndata._core.views' (/Users/luisheinzlmeier/miniforge3/envs/test/lib/python3.14/site-packages/anndata/_core/views.py)
```

Versions:
```
>>> import session_info2; print(session_info2.session_info(dependencies=True)._repr_mimebundle_()["text/markdown"])
<sys>:0: RuntimeWarning: Failed to import dependencies for application/vnd.jupyter.widget-view+json representation. (ModuleNotFoundError: No module named 'ipywidgets')
| Dependency         | Version     |
| ------------------ | ----------- |
| h5py               | 3.16.0      |
| anndata            | 0.12.17     |
| numba              | 0.65.1      |
| cytoolz            | 1.1.0       |
| donfig             | 0.8.1.post1 |
| scverse-misc       | 0.0.8       |
| fonttools          | 4.63.0      |
| scikit-learn       | 1.9.0       |
| numpy              | 2.4.6       |
| setuptools         | 82.0.1      |
| kiwisolver         | 1.5.0       |
| zarr               | 3.2.1       |
| packaging          | 26.2        |
| joblib             | 1.5.3       |
| charset-normalizer | 3.4.7       |
| six                | 1.17.0      |
| scipy              | 1.17.1      |
| pyarrow            | 24.0.0      |
| PyYAML             | 6.0.3       |
| cloudpickle        | 3.1.2       |
| Jinja2             | 3.1.6       |
| pandas             | 2.3.3       |
| docrep             | 0.3.2       |
| lz4                | 4.4.5       |
| pillow             | 12.2.0      |
| fsspec             | 2026.6.0    |
| threadpoolctl      | 3.6.0       |
| cycler             | 0.12.1      |
| numcodecs          | 0.16.5      |
| msgpack            | 1.1.2       |
| tblib              | 3.2.2       |
| xarray             | 2026.4.0    |
| toolz              | 1.1.0       |
| legacy-api-wrap    | 1.5         |
| session-info2      | 0.4.1       |
| google-crc32c      | 1.8.0       |
| python-dateutil    | 2.9.0.post0 |
| psutil             | 7.2.2       |
| pyparsing          | 3.3.2       |
| dask               | 2026.6.0    |
| MarkupSafe         | 3.0.3       |
| natsort            | 8.4.0       |
| pytz               | 2026.2      |
| fast-array-utils   | 1.4.1       |
| matplotlib         | 3.11.0      |
| narwhals           | 2.22.1      |
| llvmlite           | 0.47.0      |
| typing_extensions  | 4.15.0      |
| scanpy             | 1.12.1      |

| Component | Info                                                                             |
| --------- | -------------------------------------------------------------------------------- |
| Python    | 3.14.6 | packaged by conda-forge | (main, Jun 12 2026, 08:47:56) [Clang 20.1.8 ] |
| OS        | macOS-15.7.4-arm64-arm-64bit-Mach-O                                              |
| Updated   | 2026-06-17 11:32                                                                 |
```

**Comment by selmanozleyen** [comment]
Hi thanks for the info but did you install the latest squidpy? This problem is probably in the conda releases I'd guess

**Comment by LuisHeinzlmeier** [comment]
Ah, I see, thank you! Yes, it was conda, and it somehow installed `squidpy 1.2.2`! Sorry for bringing this up.
